# This is a config for E2B sandbox template.
# You can use template ID (d54kfz9zmh32iczuh0yw) or template name (vibeit-nextjs-test-4) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibeit-nextjs-test-4") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibeit-nextjs-test-4") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibeit-nextjs-test-4')

team_id = "1f961dfb-6a22-4c32-a5c6-b26ad4e3ace7"
start_cmd = "bash compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibeit-nextjs-test-4"
template_id = "d54kfz9zmh32iczuh0yw"
